/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.Business;
import static Business.Organization.Organization.TypeofOrg.Customer;
import Business.User.Customer;
import UserInterface.Admin.*;
import UserInterface.PostContainerJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class CustomerWorkareaJPanel extends javax.swing.JPanel {

    private Business business;
    private Customer customer;

    /**
     * Creates new form AdminWorkareaJPanel
     */
    public CustomerWorkareaJPanel(Customer customer) {
        initComponents();
        this.business = Business.getInstance();
        this.customer = customer;
        populateHomeArea();
        if (customer.getSurvey() == null) {
            pushSurvey();
        }
    }

    public void populateHomeArea() {
        PostContainerJPanel panel = new PostContainerJPanel(userProcessContainer, business.getOrgDirectory().getRestaurantOrganization(), customer.getCart());
        userProcessContainer.add("PostContainerJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }

    public void pushSurvey() {
        int dialogButton = JOptionPane.YES_OPTION;
        int result = JOptionPane.showConfirmDialog(null,
                "Take survey?",
                "Take your survey",
                dialogButton);
        if (JOptionPane.YES_OPTION == result) {
            SurveyJPanel panel = new SurveyJPanel(userProcessContainer, customer);
            userProcessContainer.add("SurveyJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel5 = new javax.swing.JPanel();
        splitWorkarea = new javax.swing.JSplitPane();
        indexJPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btMyDiet = new javax.swing.JButton();
        btMyCart = new javax.swing.JButton();
        btMyProfile = new javax.swing.JButton();
        btMyCalorieTrace = new javax.swing.JButton();
        btMySurvey = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        splitWorkarea.setDividerLocation(250);
        splitWorkarea.setDividerSize(4);
        splitWorkarea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        indexJPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("My Order");
        jButton1.setPreferredSize(new java.awt.Dimension(170, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jButton1, gridBagConstraints);

        btMyDiet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btMyDiet.setText("My Diet");
        btMyDiet.setPreferredSize(new java.awt.Dimension(170, 40));
        btMyDiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMyDietActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(btMyDiet, gridBagConstraints);

        btMyCart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btMyCart.setText("My Cart");
        btMyCart.setPreferredSize(new java.awt.Dimension(170, 40));
        btMyCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMyCartActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(btMyCart, gridBagConstraints);

        btMyProfile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btMyProfile.setText("My Profile");
        btMyProfile.setPreferredSize(new java.awt.Dimension(170, 40));
        btMyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMyProfileActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(btMyProfile, gridBagConstraints);

        btMyCalorieTrace.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btMyCalorieTrace.setText("My Calorie Trace");
        btMyCalorieTrace.setPreferredSize(new java.awt.Dimension(170, 40));
        btMyCalorieTrace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMyCalorieTraceActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(btMyCalorieTrace, gridBagConstraints);

        btMySurvey.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btMySurvey.setText("My Survey");
        btMySurvey.setPreferredSize(new java.awt.Dimension(170, 40));
        btMySurvey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMySurveyActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(btMySurvey, gridBagConstraints);

        javax.swing.GroupLayout indexJPanelLayout = new javax.swing.GroupLayout(indexJPanel);
        indexJPanel.setLayout(indexJPanelLayout);
        indexJPanelLayout.setHorizontalGroup(
            indexJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexJPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        indexJPanelLayout.setVerticalGroup(
            indexJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexJPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        splitWorkarea.setLeftComponent(indexJPanel);

        userProcessContainer.setBackground(new java.awt.Color(255, 255, 255));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        splitWorkarea.setRightComponent(userProcessContainer);

        jPanel5.add(splitWorkarea, java.awt.BorderLayout.CENTER);

        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btMyCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMyCartActionPerformed
        // TODO add your handling code here:
        CartJPanel panel = new CartJPanel(userProcessContainer, customer.getOrderDirectory(), customer);
        userProcessContainer.add("CartJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btMyCartActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ManageCustomerOrderJPanel panel = new ManageCustomerOrderJPanel(userProcessContainer, customer.getOrderDirectory());
        userProcessContainer.add("ManageCustomerOrderJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btMyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMyProfileActionPerformed
        // TODO add your handling code here:
        CustomerProfileJPanel panel = new CustomerProfileJPanel(userProcessContainer, customer);
        userProcessContainer.add("CustomerProfileJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btMyProfileActionPerformed

    private void btMyCalorieTraceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMyCalorieTraceActionPerformed
        // TODO add your handling code here:
        CustomerCalorieTraceJPanel panel = new CustomerCalorieTraceJPanel(userProcessContainer, customer);
        userProcessContainer.add("CustomerCalorieTraceJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btMyCalorieTraceActionPerformed

    private void btMyDietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMyDietActionPerformed
        // TODO add your handling code here:
        if (customer.getSurvey() == null) {
            JOptionPane.showMessageDialog(null, "Please take the survey first.");
            return;
        }
        CustomerDietJPanel panel = new CustomerDietJPanel(userProcessContainer, customer);
        userProcessContainer.add("CustomerDietJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btMyDietActionPerformed

    private void btMySurveyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMySurveyActionPerformed
        // TODO add your handling code here:
        if (customer.getSurvey() == null) {
            JOptionPane.showMessageDialog(null, "Please take the survey first.");
            return;
        }
        SurveyJPanel panel = new SurveyJPanel(userProcessContainer, customer);
        userProcessContainer.add("SurveyJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btMySurveyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMyCalorieTrace;
    private javax.swing.JButton btMyCart;
    private javax.swing.JButton btMyDiet;
    private javax.swing.JButton btMyProfile;
    private javax.swing.JButton btMySurvey;
    private javax.swing.JPanel indexJPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSplitPane splitWorkarea;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
