/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.Diet.Allergy;
import Business.Diet.EatingHabbit;
import Business.Ingredient.Ingredient;
import Business.Survey.Survey;
import Business.Survey.Survey.TrendType;
import Business.User.Customer;
import DataManagement.DatabaseFactory;
import UserInterface.MainJFrame;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Alex
 */
public class SurveyJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Customer customer;

    /**
     * Creates new form SurveyJPanel
     */
    public SurveyJPanel(JPanel userProcessContainer, Customer customer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customer = customer;
        populateEatingHabbitArea();
        populateAllergyArea();
        if (customer.getSurvey() != null) {
            populatePreviousSurvey();
        }
    }

    private void populatePreviousSurvey() {
        float budgetMin = customer.getSurvey().getBudgetMin();
        if (budgetMin == 0) {
            rd0_10.setSelected(true);
        } else if (budgetMin == 10) {
            rd10_20.setSelected(true);
        } else if (budgetMin == 21) {
            rd21_30.setSelected(true);
        } else if (budgetMin == 31) {
            rd31_40.setSelected(true);
        } else if (budgetMin == 41) {
            rd41_50.setSelected(true);
        } else if (budgetMin == 51) {
            rd51_100.setSelected(true);
        } else if (budgetMin == 101) {
            rd101_more.setSelected(true);
        }

        Survey.TrendType trendType = customer.getSurvey().getTrent();
        if (trendType == TrendType.LoseWeight) {
            radioLoseWeight.setSelected(true);
        } else if (trendType == TrendType.GainWeight) {
            radioGainWeight.setSelected(true);
        } else {
            radioImGood.setSelected(true);
        }

        DefaultListModel listModel = (DefaultListModel) listHabbit.getModel();
        int[] eatingHabbitIndices = new int[customer.getSurvey().getEatingHabbit().getIngredientTypeList().size()];
        int index = 0;
        for (Ingredient.IngredientType type : customer.getSurvey().getEatingHabbit().getIngredientTypeList()) {
            eatingHabbitIndices[index] = listModel.indexOf(type);
            index++;
        }
        listHabbit.setSelectedIndices(eatingHabbitIndices);

        listModel = (DefaultListModel) listAllergy.getModel();
        int[] allergyIndices = new int[customer.getSurvey().getAllergy().getIngredientTypeList().size()];
        index = 0;
        for (Ingredient.IngredientType type : customer.getSurvey().getAllergy().getIngredientTypeList()) {
            allergyIndices[index] = listModel.indexOf(type);
            index++;
        }
        listAllergy.setSelectedIndices(allergyIndices);
    }

    public void populateEatingHabbitArea() {
        DefaultListModel model = new DefaultListModel();
        listHabbit.setModel(model);
        for (Ingredient.IngredientType type : Ingredient.IngredientType.values()) {
            model.addElement(type);
        }
    }

    public void populateAllergyArea() {
        DefaultListModel model = new DefaultListModel();
        listAllergy.setModel(model);
        for (Ingredient.IngredientType type : Ingredient.IngredientType.values()) {
            model.addElement(type);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupBudget = new javax.swing.ButtonGroup();
        buttonGroupTrend = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rd0_10 = new javax.swing.JRadioButton();
        rd10_20 = new javax.swing.JRadioButton();
        rd21_30 = new javax.swing.JRadioButton();
        rd31_40 = new javax.swing.JRadioButton();
        rd41_50 = new javax.swing.JRadioButton();
        rd51_100 = new javax.swing.JRadioButton();
        rd101_more = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listHabbit = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAllergy = new javax.swing.JList();
        btSubmit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        radioLoseWeight = new javax.swing.JRadioButton();
        radioGainWeight = new javax.swing.JRadioButton();
        radioImGood = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setText("What's your budget per day?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel1, gridBagConstraints);

        rd0_10.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupBudget.add(rd0_10);
        rd0_10.setText("Under 10$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(rd0_10, gridBagConstraints);

        rd10_20.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupBudget.add(rd10_20);
        rd10_20.setSelected(true);
        rd10_20.setText("10$ ~ 20$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(rd10_20, gridBagConstraints);

        rd21_30.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupBudget.add(rd21_30);
        rd21_30.setText("21$ ~ 30$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(rd21_30, gridBagConstraints);

        rd31_40.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupBudget.add(rd31_40);
        rd31_40.setText("31$ ~ 40$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(rd31_40, gridBagConstraints);

        rd41_50.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupBudget.add(rd41_50);
        rd41_50.setText("41$ ~ 50$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(rd41_50, gridBagConstraints);

        rd51_100.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupBudget.add(rd51_100);
        rd51_100.setText("51$ ~ 100$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(rd51_100, gridBagConstraints);

        rd101_more.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupBudget.add(rd101_more);
        rd101_more.setText("More than 100$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(rd101_more, gridBagConstraints);

        jLabel2.setText("Please select the ingredient you like:");

        jLabel3.setText("Please select your allergy:");

        jScrollPane3.setViewportView(listHabbit);

        jScrollPane1.setViewportView(listAllergy);

        btSubmit.setText("Submit");
        btSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubmitActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        jPanel2Layout.rowHeights = new int[] {0, 5, 0, 5, 0};
        jPanel2.setLayout(jPanel2Layout);

        jLabel4.setText("Do you want to?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jLabel4, gridBagConstraints);

        radioLoseWeight.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupTrend.add(radioLoseWeight);
        radioLoseWeight.setText("Lose weight");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(radioLoseWeight, gridBagConstraints);

        radioGainWeight.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupTrend.add(radioGainWeight);
        radioGainWeight.setText("Gain weight");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(radioGainWeight, gridBagConstraints);

        radioImGood.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupTrend.add(radioImGood);
        radioImGood.setSelected(true);
        radioImGood.setText("I'm good");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(radioImGood, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(81, 81, 81)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(262, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSubmit)
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubmitActionPerformed
        // TODO add your handling code here:
        float budgetMin = 0;
        float budgetMax = 0;
        if (rd0_10.isSelected()) {
            budgetMin = 0;
            budgetMax = 9;
        } else if (rd10_20.isSelected()) {
            budgetMin = 10;
            budgetMax = 20;
        } else if (rd21_30.isSelected()) {
            budgetMin = 21;
            budgetMax = 30;
        } else if (rd31_40.isSelected()) {
            budgetMin = 31;
            budgetMax = 40;
        } else if (rd41_50.isSelected()) {
            budgetMin = 41;
            budgetMax = 50;
        } else if (rd51_100.isSelected()) {
            budgetMin = 51;
            budgetMax = 100;
        } else {
            budgetMin = 101;
            budgetMax = 9999;
        }
        Survey.TrendType trendType;
        if (radioLoseWeight.isSelected()) {
            trendType = Survey.TrendType.LoseWeight;
        } else if (radioGainWeight.isSelected()) {
            trendType = Survey.TrendType.GainWeight;
        } else {
            trendType = Survey.TrendType.Remain;
        }

        Survey survey = null;
        if (customer.getSurvey() == null) {
            survey = new Survey();
            customer.setSurvey(survey);
        } else {
            survey = customer.getSurvey();
        }
        survey.setBudgetMin(budgetMin);
        survey.setBudgetMax(budgetMax);
        survey.setTrent(trendType);

        survey.getEatingHabbit().getIngredientTypeList().clear();
        List<Ingredient.IngredientType> habbitList = listHabbit.getSelectedValuesList();
        for (Ingredient.IngredientType type : habbitList) {
            survey.getEatingHabbit().getIngredientTypeList().add(type);
        }

        survey.getAllergy().getIngredientTypeList().clear();
        List<Ingredient.IngredientType> allergyList = listAllergy.getSelectedValuesList();
        for (Ingredient.IngredientType type : allergyList) {
            survey.getAllergy().getIngredientTypeList().add(type);
        }
        DatabaseFactory.getInstance().storeSystem();
        JOptionPane.showMessageDialog(null, "Thank you. Now you can go to your diet.");

//        userProcessContainer.remove(this);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSubmit;
    private javax.swing.ButtonGroup buttonGroupBudget;
    private javax.swing.ButtonGroup buttonGroupTrend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listAllergy;
    private javax.swing.JList listHabbit;
    private javax.swing.JRadioButton radioGainWeight;
    private javax.swing.JRadioButton radioImGood;
    private javax.swing.JRadioButton radioLoseWeight;
    private javax.swing.JRadioButton rd0_10;
    private javax.swing.JRadioButton rd101_more;
    private javax.swing.JRadioButton rd10_20;
    private javax.swing.JRadioButton rd21_30;
    private javax.swing.JRadioButton rd31_40;
    private javax.swing.JRadioButton rd41_50;
    private javax.swing.JRadioButton rd51_100;
    // End of variables declaration//GEN-END:variables
}
