/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerService;

import Business.Business;
import Business.Survey.Survey;
import Business.User.Customer;
import Business.User.Restaurant;
import Business.UserAccount.UserAccount;
import DataManagement.DatabaseFactory;
import UserInterface.Customer.CartJPanel;
import UserInterface.Customer.CustomerProfileJPanel;
import UserInterface.Customer.ManageCustomerOrderJPanel;
import UserInterface.Customer.SurveyJPanel;
import UserInterface.Restaurant.RestaurantProfileJPanel;
import UserInterface.Sales.*;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex
 */
public class ManageCustomerJPanel extends javax.swing.JPanel {

    Business business;
    JPanel userProcessContainer;

    /**
     * Creates new form ManageRestaurantJPanel
     */
    public ManageCustomerJPanel(JPanel userProcessContainer) {
        initComponents();
        business = Business.getInstance();
        this.userProcessContainer = userProcessContainer;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblCustomer.getModel();
        model.setRowCount(0);
        for (Customer c : business.getOrgDirectory().getCustomerOrganization().getAllCustomer()) {
            Object[] row = new Object[5];
            row[0] = c.getUserId();
            row[1] = c;
            row[2] = c.getAge();
            row[3] = c.getLocationArea();
            row[4] = c.getAddress();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        btUpdateCustomerProfile = new javax.swing.JButton();
        btManageCustomerCart = new javax.swing.JButton();
        btManageCustomerOrder = new javax.swing.JButton();
        btManageCustomerSurvey = new javax.swing.JButton();
        btDisableCustomer = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Age", "Location", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        btUpdateCustomerProfile.setText("Update Customer Profile");
        btUpdateCustomerProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateCustomerProfileActionPerformed(evt);
            }
        });

        btManageCustomerCart.setText("Manage Customer Cart");
        btManageCustomerCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btManageCustomerCartActionPerformed(evt);
            }
        });

        btManageCustomerOrder.setText("Manage Customer Order");
        btManageCustomerOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btManageCustomerOrderActionPerformed(evt);
            }
        });

        btManageCustomerSurvey.setText("Manage Customer Survey");
        btManageCustomerSurvey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btManageCustomerSurveyActionPerformed(evt);
            }
        });

        btDisableCustomer.setText("Disable Customer");
        btDisableCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDisableCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btUpdateCustomerProfile)
                        .addGap(18, 18, 18)
                        .addComponent(btManageCustomerOrder)
                        .addGap(18, 18, 18)
                        .addComponent(btManageCustomerCart)
                        .addGap(18, 18, 18)
                        .addComponent(btManageCustomerSurvey)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btDisableCustomer)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btUpdateCustomerProfile)
                    .addComponent(btManageCustomerOrder)
                    .addComponent(btManageCustomerCart)
                    .addComponent(btManageCustomerSurvey)
                    .addComponent(btDisableCustomer))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btUpdateCustomerProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateCustomerProfileActionPerformed
        // TODO add your handling code here:
        int row = tblCustomer.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "PLease select a row.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Customer c = (Customer) tblCustomer.getValueAt(row, 1);

        CustomerProfileJPanel panel = new CustomerProfileJPanel(userProcessContainer, c);
        userProcessContainer.add("CustomerProfileJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btUpdateCustomerProfileActionPerformed

    private void btManageCustomerOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btManageCustomerOrderActionPerformed
        // TODO add your handling code here:
        int row = tblCustomer.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "PLease select a row.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Customer c = (Customer) tblCustomer.getValueAt(row, 1);

        ManageCustomerOrderJPanel panel = new ManageCustomerOrderJPanel(userProcessContainer, c.getOrderDirectory());
        userProcessContainer.add("ManageCustomerOrderJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btManageCustomerOrderActionPerformed

    private void btManageCustomerCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btManageCustomerCartActionPerformed
        // TODO add your handling code here:
        int row = tblCustomer.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "PLease select a row.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Customer c = (Customer) tblCustomer.getValueAt(row, 1);

        CartJPanel panel = new CartJPanel(userProcessContainer, c.getOrderDirectory(), c);
        userProcessContainer.add("CartJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btManageCustomerCartActionPerformed

    private void btDisableCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDisableCustomerActionPerformed
        // TODO add your handling code here:
        int row = tblCustomer.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "PLease select a row.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Customer c = (Customer) tblCustomer.getValueAt(row, 1);
        
        c.getUserAccount().setStatus(UserAccount.AccountStatusType.Inactive);
        DatabaseFactory.getInstance().storeSystem();
        JOptionPane.showMessageDialog(null, "Disabled");
        populateTable();
    }//GEN-LAST:event_btDisableCustomerActionPerformed

    private void btManageCustomerSurveyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btManageCustomerSurveyActionPerformed
        // TODO add your handling code here:
        int row = tblCustomer.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "PLease select a row.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Customer c = (Customer) tblCustomer.getValueAt(row, 1);

        SurveyJPanel panel = new SurveyJPanel(userProcessContainer, c);
        userProcessContainer.add("SurveyJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btManageCustomerSurveyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDisableCustomer;
    private javax.swing.JButton btManageCustomerCart;
    private javax.swing.JButton btManageCustomerOrder;
    private javax.swing.JButton btManageCustomerSurvey;
    private javax.swing.JButton btUpdateCustomerProfile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomer;
    // End of variables declaration//GEN-END:variables
}
