/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Restaurant;

import UserInterface.Admin.*;
import Business.Role.CustomerRole;
import Business.UserAccount.UserAccount;
import Business.*;
import Business.Menu.Dish;
import Business.Organization.Organization;
import Business.Role.AdminRole;
import Business.Role.CustomerServiceRole;
import Business.Role.RestaurantRole;
import Business.Role.Role;
import Business.Role.SalesRole;
import Business.User.Admin;
import Business.User.Customer;
import Business.User.CustomerService;
import Business.User.Restaurant;
import Business.User.Sales;
import Business.User.User;
import DataManagement.DatabaseFactory;
import java.awt.CardLayout;
import java.awt.FileDialog;
import java.awt.Frame;
import java.io.File;
import java.io.FilenameFilter;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Alex
 */
public class AddDishJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ManageMenuJPanel parent;
    private Business business;
    private Restaurant restaurant;

    /**
     * Creates new form AddEmploeeJPanel
     */
    public AddDishJPanel(JPanel userProcessContainer, Business business, ManageMenuJPanel parent, Restaurant restaurant) {
        initComponents();
        this.business = business;
        this.userProcessContainer = userProcessContainer;
        this.parent = parent;
        this.restaurant = restaurant;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtImage = new javax.swing.JTextField();
        btBrowse = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        spinnerPrice = new javax.swing.JSpinner();
        btBack = new javax.swing.JButton();
        btSubmit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel1, gridBagConstraints);

        txtName.setMaximumSize(new java.awt.Dimension(200, 20));
        txtName.setMinimumSize(new java.awt.Dimension(200, 20));
        txtName.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel1.add(txtName, gridBagConstraints);

        jLabel2.setText("Image:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel2, gridBagConstraints);

        txtImage.setEnabled(false);
        txtImage.setMaximumSize(new java.awt.Dimension(200, 20));
        txtImage.setMinimumSize(new java.awt.Dimension(200, 20));
        txtImage.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel1.add(txtImage, gridBagConstraints);

        btBrowse.setText("Browse");
        btBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBrowseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        jPanel1.add(btBrowse, gridBagConstraints);

        jLabel3.setText("Price:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel3, gridBagConstraints);

        spinnerPrice.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), null, Float.valueOf(1.0f)));
        spinnerPrice.setMaximumSize(new java.awt.Dimension(150, 20));
        spinnerPrice.setMinimumSize(new java.awt.Dimension(150, 20));
        spinnerPrice.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(spinnerPrice, gridBagConstraints);

        btBack.setText("<< Back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        btSubmit.setText("Add");
        btSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btBack)
                        .addGap(212, 212, 212)
                        .addComponent(btSubmit)))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBack)
                    .addComponent(btSubmit))
                .addContainerGap(262, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubmitActionPerformed
        // TODO add your handling code here:
        String name;
        String imagePath;
        float price = 0;
        try {
            name = txtName.getText().trim();
            imagePath = txtImage.getText().trim();
            price = (float) spinnerPrice.getValue();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Invalid input.");
            return;
        }
        if (name.equals("") || imagePath.equals("")) {
            JOptionPane.showMessageDialog(null, "Invalid input.");
            return;
        }
        
        Dish newDish = restaurant.getMenu().addDish();
        newDish.setName(name);
        newDish.setImagePath(imagePath);
        newDish.setPrice(price);
        newDish.setRestaurant(restaurant);
        DatabaseFactory.getInstance().storeSystem();
        JOptionPane.showMessageDialog(null, "Created");
        parent.populateDishTable();
    }//GEN-LAST:event_btSubmitActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        parent.populateDishTable();
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_btBackActionPerformed

    private void btBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBrowseActionPerformed
        // TODO add your handling code here:
        FileDialog fd = new FileDialog(new Frame(), "test", FileDialog.LOAD);
        FilenameFilter ff = new FilenameFilter() {
            public boolean accept(File dir, String name) {
                if (name.endsWith("jpg")) {
                    return true;
                }
                return false;
            }
        };
        fd.setFilenameFilter(ff);
        fd.setVisible(true);
        txtImage.setText(fd.getDirectory() + fd.getFile());
    }//GEN-LAST:event_btBrowseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btBrowse;
    private javax.swing.JButton btSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spinnerPrice;
    private javax.swing.JTextField txtImage;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
