/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Restaurant;

import Business.Order.Order;
import Business.Order.OrderItem;
import Business.Payment.Payment;
import Business.User.Restaurant;
import DataManagement.DatabaseFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.renderer.xy.DeviationRenderer;

/**
 *
 * @author Alex
 */
public class RestaurantViewOrderJPanel extends javax.swing.JPanel {

    private Restaurant restaurant;
    private JPanel userProcessContainer;

    /**
     * Creates new form RestaurantViewOrderJPanel
     */
    public RestaurantViewOrderJPanel(JPanel userProcessContainer, Restaurant restaurant) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.restaurant = restaurant;
        tblOrder.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                int selectedRow = tblOrder.getSelectedRow();
                if (selectedRow >= 0) {
                    Order o = (Order) tblOrder.getValueAt(selectedRow, 0);
                    populateOrderItem(o);
                }
            }
        });
        populateOrder();
    }

    public void populateOrder() {
        DefaultTableModel model = (DefaultTableModel) tblOrder.getModel();
        model.setRowCount(0);
        for (Order o : restaurant.getOrderDirectory().getOrderList()) {
            Object[] row = new Object[6];
            row[0] = o;
            row[1] = o.getRestaurant().getName();
            row[2] = o.getPayment().getStatus();
            row[3] = o.getTicket();
            row[4] = o.isIsConsumed() ? "Used" : "Unused";
            row[5] = row[5] = o.getConsumeTimeStamp();
            model.addRow(row);
        }
    }

    public void populateOrderItem(Order o) {
        DefaultTableModel model = (DefaultTableModel) tblOrderItem.getModel();
        model.setRowCount(0);
        for (OrderItem oi : o.getOrderItemList()) {
            Object[] row = new Object[2];
            row[0] = oi.getDish().getName();
            row[1] = oi.getQuantity();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrderItem = new javax.swing.JTable();
        btConsume = new javax.swing.JButton();
        txtCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Restaurant", "Payment Status", "Ticket", "Status", "Consume Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrder);

        tblOrderItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dishes", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblOrderItem);

        btConsume.setText("Confirm Visit / Consume");
        btConsume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsumeActionPerformed(evt);
            }
        });

        txtCode.setPreferredSize(new java.awt.Dimension(150, 20));

        jLabel1.setText("Code:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 80, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btConsume))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsume))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btConsumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsumeActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrder.getSelectedRow();
        if (selectedRow >= 0) {
            Order o = (Order) tblOrder.getValueAt(selectedRow, 0);

            if (o.getPayment().getStatus().equals(Payment.TypeofStatus.Unpaid)) {
                JOptionPane.showMessageDialog(null, "This order was not paid.");
                return;
            }

            if (o.isIsConsumed()) {
                JOptionPane.showMessageDialog(null, "This order was already consumed.");
                return;
            }

            String code = txtCode.getText().trim();
            if (o.getTicket().getCode().equals(code)) {
                o.consume();
                DatabaseFactory.getInstance().storeSystem();
                populateOrder();
                JOptionPane.showMessageDialog(null, "Confirmed");
            } else {
                JOptionPane.showMessageDialog(null, "Wrong ticket");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row.");
        }

    }//GEN-LAST:event_btConsumeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsume;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTable tblOrderItem;
    private javax.swing.JTextField txtCode;
    // End of variables declaration//GEN-END:variables
}
