/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Sales;

import Business.Organization.Organization;
import Business.Organization.SalesOrganization;
import Business.UserAccount.UserAccount;
import UserInterface.Admin.*;
import UserInterface.Restaurant.ManageMenuJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Alex
 */
public class SalesWorkareaJPanel extends javax.swing.JPanel {

    private UserAccount userAccount;
    private SalesOrganization salesOrg;

    /**
     * Creates new form AdminWorkareaJPanel
     */
    public SalesWorkareaJPanel(UserAccount userAccount, SalesOrganization salesOrg) {
        initComponents();
        this.userAccount = userAccount;
        this.salesOrg = salesOrg;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel5 = new javax.swing.JPanel();
        splitWorkarea = new javax.swing.JSplitPane();
        indexJPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btManageRestaurant = new javax.swing.JButton();
        btEnrollmentRequest = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        splitWorkarea.setDividerLocation(200);
        splitWorkarea.setDividerSize(4);
        splitWorkarea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        indexJPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 10, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        btManageRestaurant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btManageRestaurant.setText("Manage Restaurant");
        btManageRestaurant.setPreferredSize(new java.awt.Dimension(170, 40));
        btManageRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btManageRestaurantActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(btManageRestaurant, gridBagConstraints);

        btEnrollmentRequest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btEnrollmentRequest.setText("Enrollment Request");
        btEnrollmentRequest.setPreferredSize(new java.awt.Dimension(170, 40));
        btEnrollmentRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnrollmentRequestActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(btEnrollmentRequest, gridBagConstraints);

        javax.swing.GroupLayout indexJPanelLayout = new javax.swing.GroupLayout(indexJPanel);
        indexJPanel.setLayout(indexJPanelLayout);
        indexJPanelLayout.setHorizontalGroup(
            indexJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, indexJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        indexJPanelLayout.setVerticalGroup(
            indexJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        splitWorkarea.setLeftComponent(indexJPanel);

        userProcessContainer.setBackground(new java.awt.Color(255, 255, 255));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        splitWorkarea.setRightComponent(userProcessContainer);

        jPanel5.add(splitWorkarea, java.awt.BorderLayout.CENTER);

        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btEnrollmentRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnrollmentRequestActionPerformed
        // TODO add your handling code here:
        EnrollmentRequestJPanel panel = new EnrollmentRequestJPanel(userProcessContainer, salesOrg, userAccount);
        userProcessContainer.add("EnrollmentRequestJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btEnrollmentRequestActionPerformed

    private void btManageRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btManageRestaurantActionPerformed
        // TODO add your handling code here:
        ManageRestaurantJPanel panel = new ManageRestaurantJPanel(userProcessContainer);
        userProcessContainer.add("ManageRestaurantJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btManageRestaurantActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEnrollmentRequest;
    private javax.swing.JButton btManageRestaurant;
    private javax.swing.JPanel indexJPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSplitPane splitWorkarea;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
