/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Menu.Dish;
import Business.Order.OrderItem;
import Business.Payment.CardVerification;
import Business.Payment.Payment;
import DataManagement.DatabaseFactory;
import UserInterface.Customer.ManageCustomerOrderJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex
 */
public class PaymentJPanel extends javax.swing.JPanel {

    private Payment payment;
    private ManageCustomerOrderJPanel parent;
    private JPanel userProcessContainer;

    /**
     * Creates new form PaymentJPanel
     */
    public PaymentJPanel(JPanel userProcessContainer, Payment payment, ManageCustomerOrderJPanel parent) {
        initComponents();
        this.payment = payment;
        this.parent = parent;
        this.userProcessContainer = userProcessContainer;
        populateInfo();
        populateOrderTable();
    }

    public void populateOrderTable() {
        DefaultTableModel model = (DefaultTableModel) tblOrder.getModel();
        model.setRowCount(0);
        for (OrderItem oi : payment.getOrder().getOrderItemList()) {
            Object[] row = new Object[3];
            row[0] = payment.getOrder().getRestaurant().getName();
            row[1] = oi.getDish().getName();
            row[2] = oi.getQuantity();
            model.addRow(row);
        }
    }

    public void populateInfo() {
        txtBalance.setText(String.valueOf(payment.getBalance()));
        txtActuralPayment.setText(String.valueOf(payment.getBalance() * payment.getDiscount()));
        txtPayAtRestaurantBalance.setText(String.valueOf(payment.getBalance()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCardNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMonth = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        btOnlineSumbit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtActuralPayment = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtPayAtRestaurantBalance = new javax.swing.JTextField();
        btPayAtRestaurantSubmit = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setBackground(new java.awt.Color(255, 255, 255));

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Restaurant", "Dish", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrder);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setText("Balance:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel1, gridBagConstraints);

        txtBalance.setEnabled(false);
        txtBalance.setMaximumSize(new java.awt.Dimension(150, 20));
        txtBalance.setMinimumSize(new java.awt.Dimension(150, 20));
        txtBalance.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtBalance, gridBagConstraints);

        jLabel2.setText("Card Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel2, gridBagConstraints);

        txtCardNumber.setMaximumSize(new java.awt.Dimension(150, 20));
        txtCardNumber.setMinimumSize(new java.awt.Dimension(150, 20));
        txtCardNumber.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtCardNumber, gridBagConstraints);

        jLabel4.setText("Code:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel4, gridBagConstraints);

        txtCode.setMaximumSize(new java.awt.Dimension(150, 20));
        txtCode.setMinimumSize(new java.awt.Dimension(150, 20));
        txtCode.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtCode, gridBagConstraints);

        jLabel5.setText("Expire Date:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel5, gridBagConstraints);

        txtMonth.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtMonth, gridBagConstraints);

        txtYear.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtYear, gridBagConstraints);

        btOnlineSumbit.setText("Submit");
        btOnlineSumbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOnlineSumbitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(btOnlineSumbit, gridBagConstraints);

        jLabel6.setText("Pay after Discount:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel6, gridBagConstraints);

        txtActuralPayment.setEnabled(false);
        txtActuralPayment.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtActuralPayment, gridBagConstraints);

        jTabbedPane1.addTab("Online Payment", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 5, 0, 5, 0};
        jPanel2Layout.rowHeights = new int[] {0, 5, 0};
        jPanel2.setLayout(jPanel2Layout);

        jLabel7.setText("Balance:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jLabel7, gridBagConstraints);

        txtPayAtRestaurantBalance.setEnabled(false);
        txtPayAtRestaurantBalance.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(txtPayAtRestaurantBalance, gridBagConstraints);

        btPayAtRestaurantSubmit.setText("Submit");
        btPayAtRestaurantSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPayAtRestaurantSubmitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel2.add(btPayAtRestaurantSubmit, gridBagConstraints);

        jTabbedPane1.addTab("Pay at restaurant", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btOnlineSumbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOnlineSumbitActionPerformed
        // TODO add your handling code here:
        String cardNumber = txtCardNumber.getText().trim();
        String code = txtCode.getText().trim();
        String month = txtMonth.getText().trim();
        String year = txtYear.getText().trim();

        if (cardNumber.equals("") || code.equals("") || month.equals("") || year.equals("")) {
            JOptionPane.showMessageDialog(null, "Invalid input");
            return;
        }

        CardVerification cardVerification = CardVerification.getInstance();
        if (cardVerification.verifyCard(cardNumber, code, month, year)) {
            payment.payOnline();
            DatabaseFactory.getInstance().storeSystem();
            JOptionPane.showMessageDialog(null, "Order placed.");
            parent.populateOrder();
            userProcessContainer.remove(this);
            ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
        } else {
            JOptionPane.showMessageDialog(null, "Card verification failed.");
            return;
        }

    }//GEN-LAST:event_btOnlineSumbitActionPerformed

    private void btPayAtRestaurantSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPayAtRestaurantSubmitActionPerformed
        // TODO add your handling code here:
        payment.payOffline();
        DatabaseFactory.getInstance().storeSystem();
        JOptionPane.showMessageDialog(null, "Order placed.");
        parent.populateOrder();
        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_btPayAtRestaurantSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOnlineSumbit;
    private javax.swing.JButton btPayAtRestaurantSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextField txtActuralPayment;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtCardNumber;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtPayAtRestaurantBalance;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
