/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Cart.Cart;
import Business.Location.LocationArea;
import static Business.Organization.Organization.TypeofOrg.Restaurant;
import Business.Organization.RestaurantOrganization;
import Business.User.Restaurant;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Alex
 */
public class PostContainerJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private RestaurantOrganization restaurantOrganization;
    private ArrayList<DishesContainerJPanel> dishesContainerJPanelList;
    private Cart cart;

    /**
     * Creates new form PostContainer
     */
    public PostContainerJPanel(JPanel userProcessContainer, RestaurantOrganization restaurantOrganization, Cart cart) {
        initComponents();
        this.restaurantOrganization = restaurantOrganization;
        dishesContainerJPanelList = new ArrayList<DishesContainerJPanel>();
        this.userProcessContainer = userProcessContainer;
        this.cart = cart;
        generate();
    }

    public void filter(LocationArea.LocationAreaType type) {
        for (DishesContainerJPanel panel : dishesContainerJPanelList) {
            if (!panel.getLocationArea().equals(type)) {
                panel.setVisible(false);
            }
            else{panel.setVisible(true);}
        }
    }

    public void clearFilter() {
        for (DishesContainerJPanel panel : dishesContainerJPanelList) {
            panel.setVisible(true);
        }
    }

    private void generate() {
        ArrayList<Restaurant> restaurantList = restaurantOrganization.getAllRestaurant();
        for (Restaurant restaurant : restaurantList) {
            if (restaurant.getMenu().getDishList().size() != 0) {
                DishesContainerJPanel panel = new DishesContainerJPanel(userProcessContainer, restaurant.getMenu().getDishList(), cart, restaurant.getName());
                dishesContainerJPanelList.add(panel);
                panelMain.add(panel);
            }
        }
        Dimension dimensionMain;
        if (restaurantList.size() > 4) {
            dimensionMain = new Dimension(800, 320 * restaurantList.size());
        } else {
            dimensionMain = new Dimension(800, 800);
        }
        panelMain.setPreferredSize(dimensionMain);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelMain = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(1500, 1000));
        setPreferredSize(new java.awt.Dimension(1502, 800));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1500, 1000));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1500, 1000));

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        panelMain.setMinimumSize(new java.awt.Dimension(1500, 1000));
        panelMain.setPreferredSize(new java.awt.Dimension(1500, 800));
        panelMain.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jScrollPane1.setViewportView(panelMain);

        add(jScrollPane1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
